### ISSUE TITLE
v1.2.0 published without an index.js

### ISSUE THREAD

**Issue by MylesBorins** [sindresorhus/downgrade-root#5]
Latest published version is missing the index... this is a known race condition in npm. Likely will need a new publish

**Comment by SamVerschueren** [comment]
Don't publish with node 6. Use nvm to downgrade to 4 and publish again with a patch version. I suggest using `np` which warns you for this https://twitter.com/sindresorhus/status/742866020499660804

**Comment by silverwind** [comment]
I fixed it by removing `node_modules` before publishing. Unfortunately, 1.2.1 was another failed attempt, so we're at 1.2.2 now. Thanks guys!

**Comment by sindresorhus** [comment]
For reference, here's the relevant npm issue: https://github.com/npm/npm/issues/5082

**Comment by silverwind** [comment]
Oh, and FYI, I unpublished 1.2.0 and 1.2.1.

**Comment by sindresorhus** [comment]
@silverwind Don't worry about it. I've done it many times. It's not our faults!
